### ISSUE TITLE
ImportError: No module named pathlib

### ISSUE THREAD

**Issue by pilchita** [cloudflare/python-cloudflare#126]
I try the installation via github but i see this error

```
Traceback (most recent call last):
  File "./setup.py", line 60, in <module>
    main()
  File "./setup.py", line 54, in main
    'Programming Language :: Python :: 3.8'
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 449, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 691, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 738, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 783, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 710, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 736, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 921, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1189, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1175, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-Hy5PHO/PyYAML-6.0/setup.py", line 67, in <module>
    
ImportError: No module named pathlib
```
```
pip install -r requirements.txt
Requirement already satisfied: requests>=2.4.2 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (0.18.2)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (5.3.1)
Requirement already satisfied: jsonlines in /home/emanuel/.local/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (3.0.0)
Requirement already satisfied: beautifulsoup4 in /home/emanuel/.local/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (4.10.0)
Requirement already satisfied: attrs>=19.2.0 in /home/emanuel/.local/lib/python3.8/site-packages (from jsonlines->-r requirements.txt (line 4)) (21.4.0)
Requirement already satisfied: soupsieve>1.2 in /home/emanuel/.local/lib/python3.8/site-packages (from beautifulsoup4->-r requirements.txt (line 5)) (2.3.1)

```
any ideas?

**Comment by mahtin** [comment]
Are you running Python 2.x or Python 3.x? If it's 2.x please consider moving to a 3.x release as 2.x is end-of-life. 

If you are running a 3.x (and Python 2.x is also on the system) please make sure you're actually using `python3` & `pip3` from your command line.

**Comment by mahtin** [comment]
Nothing heard. I'm going to close this issue. If you still have issues, please reopen.
