### ISSUE TITLE
Bot Management is not Working with Python Cloudflare

### ISSUE THREAD

**Issue by nizarakbarm** [cloudflare/python-cloudflare#148]
Hello,

I am trying to use python cloudflare wrapper to activate bot fight mode with bot management from cloudflare. But it is not working as in curl manually.
When i am trying to use python wrapper:
import CloudFlare

```
def main():
    #try:
        cf = CloudFlare.CloudFlare()
        zone_info = cf.zones.get(params={'name': 'nizarakbar.id'})
        #print(zone_info)
        zone_id = zone_info[0]['id']
        print(zone_id)
        #dns_records = cf.zones.dns_records.ge{ 'fight_mode': 'true' }t(zone_id)
        #print(help(cf.zones.bot_management))
        settings_bot = cf.zones.bot_management.put(zone_id, data={'enable_js': True})
        settings_bot = cf.zones.bot_management.get(zone_id)
        print(settings_bot)
        #print(dns_records)
    #except CloudFlare.exceptions.CloudFlareAPIError as e:
    #    exit('api error: %d %s - api call failed' %(e,e))
if __name__ == '__main__':
        #dns_records = cf.zones.dns_records.ge{ 'fight_mode': 'true' }t(zone_id)
    main()
```

and executed it, it resulted with an error:
```
Traceback (most recent call last):
  File "/home/devnull/python_cloudflare/zone_get.py", line 20, in <module>
    main()
  File "/home/devnull/python_cloudflare/zone_get.py", line 12, in main
    settings_bot = cf.zones.bot_management.put(zone_id, data={'enable_js': True})
  File "/usr/lib/python3.10/site-packages/CloudFlare/cloudflare.py", line 680, in put
    return self._base.do_auth('PUT', self._parts, [identifier1, identifier2, identifier3, identifier4], params, data)
  File "/usr/lib/python3.10/site-packages/CloudFlare/cloudflare.py", line 128, in do_auth
    return self._call(method, headers, parts, identifiers, params, data, files)
  File "/usr/lib/python3.10/site-packages/CloudFlare/cloudflare.py", line 501, in _call
    raise CloudFlareAPIError(code, message)
CloudFlare.exceptions.CloudFlareAPIError
```

But it is worked well in curl:
`curl -X PUT "https://api.cloudflare.com/client/v4/zones/6a02839da5f389ad43e24a95ef183b6a/bot_management" -H "X-Auth-Email: EMAIL" -H "X-Auth-Key: APIKEY" -H "Content-Type: application/javascript" --data '{"fight_mode":true}`
output:
```
{
  "result": {
    "fight_mode": true,
    "enable_js": true,
    "session_score": false,
    "auth_id_logging": false,
    "use_latest_model": false
  },
  "success": false,
  "errors": null,
  "messages": null
}
```

Why is it working with curl manually but not working at python cloudflare with the same data ?

**Comment by mahtin** [comment]
Your request is valid. This looks like a code issue. There's two issues here.

1) The API call `/zones/:id/bot_management` does not exist on the https://api.cloudflare.com/ listing. It was added because it showed up on Cloudflare's community support pages. See https://community.cloudflare.com/t/api-support-for-bot-fight-mode-on-off/391610 for example.

2) Sadly, this library is highly dependent on the documentation being correct (and updated if a call changes). As there's no documentation on the API page for the `PUT` call, it's hard to know what's what. The `GET` call is an easy guess and that works.

That all said, it seems to work. 
```
$ DOMAIN="example.com"
$

$ cli4 /zones/:${DOMAIN}/bot_management
{
    "auth_id_logging": false,
    "enable_js": false,
    "fight_mode": false,
    "session_score": false,
    "use_latest_model": false
}
$

$ cli4 --put fight_mode=True /zones/:${DOMAIN}/bot_management
cli4: /zones/:mahtin.net/bot_management - 99998 

$

$ cli4 /zones/:${DOMAIN}/bot_management
{
    "auth_id_logging": false,
    "enable_js": true,
    "fight_mode": true,
    "session_score": false,
    "use_latest_model": false
}
$

$ cli4 --put fight_mode=False /zones/:${DOMAIN}/bot_management
cli4: /zones/:mahtin.net/bot_management - 99998 

$

$ cli4 /zones/:${DOMAIN}/bot_management
{
    "auth_id_logging": false,
    "enable_js": false,
    "fight_mode": false,
    "session_score": false,
    "use_latest_model": false
}
$
```
As you can see, there's errors; however, the `bot_management` is enabled. That's very strange. Let's try this with debug enabled.
```
$ cli4 -v --put enable_js=True /zones/:${DOMAIN}/bot_management
...
2022-09-14 12:04:41,735 - Python Cloudflare API v4 - DEBUG - Call: emulated curl command ...
       curl -X PUT "https://api.cloudflare.com/client/v4/zones/d8afaec3dd2b7f8c1b470e594a21a01d/bot_management" \
            -H "User-Agent: python-cloudflare/2.10.1/python-requests/2.27.1/python/3.9.13" \
            -H "Content-Type: application/json" \
            -H "Authorization: REDACTED" \
            --data '{'enable_js': True}' 
2022-09-14 12:04:41,886 - Python Cloudflare API v4 - DEBUG - Response: 200, application/json, b'{\n  "result": {\n    "fight_mode": false,\n    "enable_js": true,\n    "session_score": false,\n    "auth_id_logging": false,\n    "use_latest_model": false\n  },\n  "success": false,\n  "errors": null,\n  "messages": null\n}\n'
2022-09-14 12:04:41,886 - Python Cloudflare API v4 - DEBUG - Response: error 99998 
cli4: /zones/:mahtin.net/bot_management - 99998 

$
```
Note that there is valid response data (just like your `curl` command). We see the following in the response:
```
b'{\n  "result": {\n    "fight_mode": false,\n    "enable_js": true,\n    "session_score": false,\n    "auth_id_logging": false,\n    "use_latest_model": false\n  },\n
```
That's valid JSON (just printed out in raw Python style). We also see that the response is `200` - a success response. 

So where does the 99998 come from? It comes from code that does not see a successful response. In fact if you look at your `curl` response, you will see `"success": false` in the returned values. It's the `false` that causes an exception to happen.

This is a bug that should be reported to Cloudflare. Sadly it's not something that the Python library can fix.

That said, you can code around it. You can look for an exception value of `99998` and ignore it. You can do a `GET` call to confirm it works. Once this is fixed by Cloudflare, the code can be removed. 

I hope this helps. It's not perfect, but it's a way forward.

**Comment by mahtin** [comment]
I added code to the `examples` folder and uploaded it to https://github.com/cloudflare/python-cloudflare/blob/master/examples/example_bot_management.py ...
```
$ cat examples/example_bot_management.py 
#!/usr/bin/env python
"""Cloudflare API code - example"""

import os
import sys
import json
sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, os.path.abspath('..'))

import CloudFlare

def main():
    """Cloudflare API code - example"""

    try:
        zone_name = sys.argv[1]
    except IndexError:
        exit('usage: example_bot_management.py zone_name True/False')

    try:
        enable_value = sys.argv[2]
    except IndexError:
        exit('usage: example_bot_management.py zone_name True/False')

    enable_value = True if enable_value in ['true','True','1'] else False

    cf = CloudFlare.CloudFlare()

    # grab the zone identifier
    try:
        params = {'name': zone_name}
        zones = cf.zones.get(params=params)
    except CloudFlare.exceptions.CloudFlareAPIError as e:
        exit('/zone %d %s - api call failed' % (e, e))
    except Exception as e:
        exit('/zone.get - %s - api call failed' % (e))

    if len(zones) == 0:
        exit('/zones.get - %s - zones not found' % (zone_name))

    if len(zones) != 1:
        exit('/zones.get - %s - api call returned %d items' % (zone_name, len(zones)))

    zone_id = zones[0]['id']

    settings_bot = cf.zones.bot_management.get(zone_id)
    print(json.dumps(settings_bot, indent=4))

    try:
        settings_bot = cf.zones.bot_management.put(zone_id, data={'enable_js': enable_value})
    except Exception as e:
        if int(e) == 99998:
            pass
        else:
            exit("Exception: %d %s" % (int(e), str(e)))

    settings_bot = cf.zones.bot_management.get(zone_id)
    print(json.dumps(settings_bot, indent=4))

if __name__ == '__main__':
    main()
$
```
This works as follows:
```
$ examples/example_bot_management.py mahtin.net True
{
    "fight_mode": false,
    "enable_js": false,
    "session_score": false,
    "auth_id_logging": false,
    "use_latest_model": false
}
{
    "fight_mode": false,
    "enable_js": true,
    "session_score": false,
    "auth_id_logging": false,
    "use_latest_model": false
}
$

$ examples/example_bot_management.py mahtin.net False
{
    "fight_mode": false,
    "enable_js": true,
    "session_score": false,
    "auth_id_logging": false,
    "use_latest_model": false
}
{
    "fight_mode": false,
    "enable_js": false,
    "session_score": false,
    "auth_id_logging": false,
    "use_latest_model": false
}
$ 
```

**Comment by nizarakbarm** [comment]
Ok, thanks for the response.

As an alternative, i am temporary creating a new function based on requests library for bot management for now.

I will reread the code at the reply tomorrow and try it because i am sleepy now after trying to debug and create an alternative for it.

**Comment by nizarakbarm** [comment]
Yup, it is regarded as 400 bad request because success is false. After i read some code of cloudflare library wrapper internally, i found how the wrapper regarded 400 bad requests if the success value is false.

**Comment by nizarakbarm** [comment]
It is because this part at Cloudflare.py: 
```
                try:
                    response_data = json.loads(response_data)
                    if not isinstance(response_data, (dict)):
                        response_data = {'success': True,
                                         'result': response_data}
                except ValueError:
                    if response_data == '':
                        # This should really be 'null' but it isn't. Even then, it's wrong!
                        if response_code == requests.codes.ok:
                            # 200 ok
                            response_data = {'success': True,
                                             'result': None}
                        else:
                            # 3xx & 4xx errors
                            response_data = {'success': False,
                                             'code': response_code,
                                             'result': None}
```

**Comment by mahtin** [comment]
I've popped this issue into Cloudflare. Hopefully the fix will be done on the backend sometime soon. At that point, the code you mentioned will execute and return success.

**Comment by nizarakbarm** [comment]
Thank you, i think i can close this issue for now.
