### ISSUE TITLE
cloudflare-2.10.4 or 2.10.3 fails to install

### ISSUE THREAD

**Issue by kamil-shapespark** [cloudflare/python-cloudflare#153]
When trying to install `python-cloudflare` installation fails with following error message.

```
(venv) c:\Core\dev\tmp>pip install python-cloudflare
Collecting python-cloudflare
  Using cached python_cloudflare-1.0.1-py3-none-any.whl
Collecting cloudflare
  Using cached cloudflare-2.10.4.tar.gz (77 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\K\AppData\Local\Temp\pip-install-0jrcixcb\cloudflare_2952fee5307f42ae8fca367bd274d9d4\setup.py", line 49, in <module>
          main()
        File "C:\Users\K\AppData\Local\Temp\pip-install-0jrcixcb\cloudflare_2952fee5307f42ae8fca367bd274d9d4\setup.py", line 13, in main
          long_description = read_me.read()
        File "C:\Users\K\AppData\Local\Programs\Python\Python38\lib\encodings\cp1250.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x88 in position 36932: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Installation fails for: `cloudflare==2.10.4` and  `cloudflare==2.10.3` 
Installation works for: `cloudflare==2.10.2` or lower.

```
python 3.8.10, 
pip 22.3.1
OS: Windows 10
```

**Comment by mahtin** [comment]
Ok. I can check this later. It was (obviously) working for me; but that may well be a fluke. I'll be at a keyboard in a few hours.

**Comment by mahtin** [comment]
Fixed in `2.10.5` - please check. I will invalidate the `2.10.3` and `2.10.4` releases soon.

**Comment by kamil-shapespark** [comment]
WOW, thank you for such quick response! I can use older version, but wanted to let you know about the error. 
Thank you for the fix - I'll check in the morning and will let you know. 

Thanks!

**Comment by kamil-shapespark** [comment]
I confirm, no issues now. Thank you for such a quick response. 👍
