### ISSUE TITLE
Installing package takes too long with poetry

### ISSUE THREAD

**Issue by donghhan** [cloudflare/python-cloudflare#165]
I am using Poetry version 1.2.1 but it takes too long to install pacakge. Here's the console message that appears (it didn't show any error message though).

```
Using version ^2.11.6 for cloudflare

Updating dependencies
Resolving dependencies... (0.1s)

Package operations: 4 installs, 0 updates, 0 removals

  • Installing attrs (23.1.0): Pending...
```

**Comment by mahtin** [comment]
I'm sorry to say I've never used `poetry`. However, try installing each package one-at-a-time. Plus provide a `poetry show --tree` output. In reality I'm not sure I'm much help.

**Comment by donghhan** [comment]
@mahtin I managed to change with using `pipenv` for my Django project virtual environment. Poetry seems to be still so sketchy for me. 

However, now it spits another error that `ModuleNotFoundError: No module named 'cloudflare'`.

Full traceback shows as follows:

```
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/apensia/Library/Caches/pypoetry/virtualenvs/letsh-api-egleQq2d-py3.11/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/apensia/Library/Caches/pypoetry/virtualenvs/letsh-api-egleQq2d-py3.11/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/Users/apensia/Library/Caches/pypoetry/virtualenvs/letsh-api-egleQq2d-py3.11/lib/python3.11/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/Users/apensia/Library/Caches/pypoetry/virtualenvs/letsh-api-egleQq2d-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/apensia/Library/Caches/pypoetry/virtualenvs/letsh-api-egleQq2d-py3.11/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/apensia/Library/Caches/pypoetry/virtualenvs/letsh-api-egleQq2d-py3.11/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/apensia/Library/Caches/pypoetry/virtualenvs/letsh-api-egleQq2d-py3.11/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/Users/apensia/Library/Caches/pypoetry/virtualenvs/letsh-api-egleQq2d-py3.11/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/apensia/dev/letsh-api/photos/models.py", line 4, in <module>
    from cloudflare import Cloudflare
ModuleNotFoundError: No module named 'cloudflare'
```


And here is how my Pipfile looks like: 

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django = "*"
pillow = "*"
dj-database-url = "*"
black = "*"
gunicorn = "*"
psycopg2-binary = "*"
django-cities-light = "*"
drf-yasg = "*"
djangorestframework-simplejwt = "*"
django-cors-headers = "*"
whitenoise = "*"
cloudflare = "*"

[dev-packages]

[requires]
python_version = "3.11"
```

**Comment by mahtin** [comment]
Case sensitive. It's `CloudFlare` (because of some long long time ago reasons) [1].
```
import CloudFlare
```
Or:
```
from CloudFlare import CloudFlare
```
See the README or the `examples` folder.

[1] https://blog.cloudflare.com/time-for-an-update/

**Comment by donghhan** [comment]
It successfully worked and installed with charm. Thank you. 
If any errors happen again, I will upload another issue. Closing this issue.
