### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x88 in position 16820: illegal multibyte sequence

### ISSUE THREAD

**Issue by wangyikun** [cloudflare/python-cloudflare#176]
When running pip install cloudflare on Windows with python 3.8, throw error:
Collecting cloudflare
  Using cached cloudflare-2.12.4.tar.gz (85 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\X\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\X\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\X\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\X\AppData\Local\Temp\pip-build-env-5nz4p9tx\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\X\AppData\Local\Temp\pip-build-env-5nz4p9tx\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\X\AppData\Local\Temp\pip-build-env-5nz4p9tx\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\X\AppData\Local\Temp\pip-build-env-5nz4p9tx\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 49, in <module>
        File "<string>", line 13, in main
      UnicodeDecodeError: 'gbk' codec can't decode byte 0x88 in position 16820: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by mahtin** [comment]
Yup - this is fixed in #175 and I'll produce a release in a few minutes. The exact reason this started failing is because I added Unicode chars into the README file (which I've now removed). Please upgrade in a bit when you see release 2.13.1 release live.

**Comment by mahtin** [comment]
`2.13.1` released at https://pypi.org/project/cloudflare/
