### ISSUE TITLE
No firewall.rules in module

### ISSUE THREAD

**Issue by kiriharu** [cloudflare/python-cloudflare#77]
I trying to use[ this](https://api.cloudflare.com/#firewall-rules-properties) api method, but i get error:

```
Traceback (most recent call last):
  File "Projects/tg/cloudflare_bot/main.py", line 138, in <module>
    pprint(cf.get_fw_rules(data['id']))
  File "Projects/tg/cloudflare_bot/main.py", line 28, in get_fw_rules
    return self.zones.firewall.rules.get(identifier)
AttributeError: '_add_unused' object has no attribute 'rules'
```

Code:

```

class CFAPI(CloudFlare):

    def __init__(self, token, email):
        super().__init__(token=token, email=email, debug=True)

    def get_fw_rules(self, identifier):
        #print(dir(self.zones.firewall))
        return self.zones.firewall.rules.get(identifier)

cf = CFAPI(CLOUDFLARE_API, CLOUDFLARE_EMAIL)
pprint(cf.get_fw_rules(data['id']))
```

I tried to check this with dir(self.zones.firewall), but I didn’t get rules in the list. Can you fix this?

**Comment by kiriharu** [comment]
Fixed by adding self.add('AUTH', "zones", "firewall/rules") to the my class, but issue still active.

**Comment by mahtin** [comment]
`firewall/rules` and more added. See `2.4.3` release on GitHub and https://pypi.org/project/cloudflare/
