### ISSUE TITLE
Trying to use X-Auth-Key instead of X-Auth-Token?

### ISSUE THREAD

**Issue by madchap** [cloudflare/python-cloudflare#79]
Hi,

First time user of this module, with v. 2.3.0 from pypi.

I am doing the very simple example of listing zones. I generated an API token.

```
 def get_cf_dns(cftoken):                          
      cf = CloudFlare.CloudFlare(debug=True, token=cftoken)                                                                                        
      zones = cf.zones.get()                        
      for zone in zones:                            
          zone_id = zone['id']                      
          zone_name = zone['name']                  
          print(zone_id, zone_name)
```

The output throws me off with 

```
2019-10-21 19:58:22,764 - Python Cloudflare API v4 - DEBUG - Response: url https://api.cloudflare.com/client/v4/zones
2019-10-21 19:58:22,764 - Python Cloudflare API v4 - DEBUG - Response: 400, application/json, {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}
2019-10-21 19:58:22,764 - Python Cloudflare API v4 - DEBUG - Response: error 6003 Invalid request headers
Traceback (most recent call last):
  File "./main.py", line 39, in <module>
    get_cf_dns(cftoken)
  File "./main.py", line 30, in get_cf_dns
    zones = cf.zones.get()
  File "/home/xxx/.virtualenvs/cloudflare_vault_py-a7RkIZod/lib/python3.7/site-packages/CloudFlare/cloudflare.py", line 618, in get
    params, data)
  File "/home/xxx/.virtualenvs/cloudflare_vault_py-a7RkIZod/lib/python3.7/site-packages/CloudFlare/cloudflare.py", line 75, in call_with_auth
    params, data, files)
  File "/home/xxx/.virtualenvs/cloudflare_vault_py-a7RkIZod/lib/python3.7/site-packages/CloudFlare/cloudflare.py", line 467, in _call
    raise CloudFlareAPIError(code, message, error_chain)
CloudFlare.exceptions.CloudFlareAPIError: Invalid request headers
```

It's talking about the X-Auth-Key header, whereas I am guessing it should not since it is really a token and I am not passing any email parameter?

I validated my token against CF with curl, all good and sound:
```
{
  "result": {
    "id": "xxx",
    "status": "active"
  },
  "success": true,
  "errors": [],
  "messages": [
    {
      "code": 10000,
      "message": "This API Token is valid and active",
      "type": null
    }
  ]
}
```

Thanks.

**Comment by madchap** [comment]
Tried with .cloudflare.cfg and hard-coded value just in case for the token, got new token.. same result.

**Comment by mnordhoff** [comment]
The current release doesn't support API tokens. You have to either use your API key, or run python-cloudflare from git.

See issue #74 and PR #76.

**Comment by madchap** [comment]
I see, thanks. I was misled by the README. Cheers.

**Comment by hadifarnoud** [comment]
I have set api key and cert in env
```
export CF_API_KEY='*****'
export CF_API_CERTKEY='v1.0-4606b5e1******'
```

but still get the same error as described here
```
Python Cloudflare API v4 - DEBUG - Call: emulated curl command ...
       curl -X GET "https://api.cloudflare.com/client/v4/zones?name=pktsrv3.com&per_page=1" \
            -H "User-Agent: python-cloudflare/2.8.15/python-requests/2.26.0/python/3.9.7" \
            -H "Content-Type: application/json" \
            -H "Authorization: REDACTED" 
2021-12-19 17:19:52,357 - Python Cloudflare API v4 - DEBUG - Response: 400, application/json, b'{"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null}'
2021-12-19 17:19:52,357 - Python Cloudflare API v4 - DEBUG - Response: error 6111 Invalid format for Authorization header - chain
2021-12-19 17:19:52,357 - Python Cloudflare API v4 - DEBUG - Response: error 6003 Invalid request headers
Traceback (most recent call last):
  File "/Users/hadifarnoud/Downloads/cf.py", line 31, in <module>
    main()
  File "/Users/hadifarnoud/Downloads/cf.py", line 24, in main
    zones = cf.zones(params=params)
  File "/opt/homebrew/lib/python3.9/site-packages/CloudFlare/cloudflare.py", line 662, in __call__
    return self.get(identifier1, identifier2, identifier3, params, data)
  File "/opt/homebrew/lib/python3.9/site-packages/CloudFlare/cloudflare.py", line 672, in get
    return self._base.call_with_auth('GET', self._parts,
  File "/opt/homebrew/lib/python3.9/site-packages/CloudFlare/cloudflare.py", line 126, in call_with_auth
    return self._call(method, headers, parts,
  File "/opt/homebrew/lib/python3.9/site-packages/CloudFlare/cloudflare.py", line 498, in _call
    raise CloudFlareAPIError(code, message, error_chain)
CloudFlare.exceptions.CloudFlareAPIError: Invalid request headers
```
